apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "growi.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "growi.name" . }}
    helm.sh/chart: {{ include "growi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "growi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "growi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: "port3000"
          containerPort: 3000
          protocol: TCP
        env:
        - name: MONGO_URI
          value: "mongodb://{{ .Release.Name }}-mongodb:27017/growi"
        - name: FILE_UPLOAD
          value: {{ .Values.settings.fileupload }}
        {{- with .Values.settings.appsiteurl }}
        - name: APP_SITE_URL
          value: {{ . }}
        {{- end }}
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: 3000
        #readinessProbe:
        #  httpGet:
        #    path: /
        #    port: 3000
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
