apiVersion: v1
entries:
  growi:
  - apiVersion: v1
    appVersion: 3.4.2
    created: 2019-03-29T00:28:18.3731334+09:00
    description: A Helm chart growi for Kubernetes
    digest: fb356bd78ef5d44121da063cd8210570c4fee1400c40a0f23299178b562803b3
    name: growi
    urls:
    - https://raw.githubusercontent.com/george-pon/growi-helm-chart/master/helm-chart/charts/growi-3.4.2.0.tgz
    version: 3.4.2.0
generated: 2019-03-29T00:28:18.370206+09:00
